/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/amendAccept': RouteRecordInfo<'/amendAccept', '/amendAccept', Record<never, never>, Record<never, never>>,
    '/amendAdjustment': RouteRecordInfo<'/amendAdjustment', '/amendAdjustment', Record<never, never>, Record<never, never>>,
    '/amendApp': RouteRecordInfo<'/amendApp', '/amendApp', Record<never, never>, Record<never, never>>,
    '/amendLcApp': RouteRecordInfo<'/amendLcApp', '/amendLcApp', Record<never, never>, Record<never, never>>,
    '/cancelAdjustment': RouteRecordInfo<'/cancelAdjustment', '/cancelAdjustment', Record<never, never>, Record<never, never>>,
    '/cancelApp': RouteRecordInfo<'/cancelApp', '/cancelApp', Record<never, never>, Record<never, never>>,
    '/chargeAmendLc': RouteRecordInfo<'/chargeAmendLc', '/chargeAmendLc', Record<never, never>, Record<never, never>>,
    '/chargeLc': RouteRecordInfo<'/chargeLc', '/chargeLc', Record<never, never>, Record<never, never>>,
    '/currentAmendApp': RouteRecordInfo<'/currentAmendApp', '/currentAmendApp', Record<never, never>, Record<never, never>>,
    '/currentAmendDraftApp': RouteRecordInfo<'/currentAmendDraftApp', '/currentAmendDraftApp', Record<never, never>, Record<never, never>>,
    '/currentCancelApp': RouteRecordInfo<'/currentCancelApp', '/currentCancelApp', Record<never, never>, Record<never, never>>,
    '/draftAdjustment': RouteRecordInfo<'/draftAdjustment', '/draftAdjustment', Record<never, never>, Record<never, never>>,
    '/draftApp': RouteRecordInfo<'/draftApp', '/draftApp', Record<never, never>, Record<never, never>>,
    '/draftRejection': RouteRecordInfo<'/draftRejection', '/draftRejection', Record<never, never>, Record<never, never>>,
    '/expiredLc': RouteRecordInfo<'/expiredLc', '/expiredLc', Record<never, never>, Record<never, never>>,
    '/fpcBenBuImp': RouteRecordInfo<'/fpcBenBuImp', '/fpcBenBuImp', Record<never, never>, Record<never, never>>,
    '/fpcCadSdi': RouteRecordInfo<'/fpcCadSdi', '/fpcCadSdi', Record<never, never>, Record<never, never>>,
    '/info': RouteRecordInfo<'/info', '/info', Record<never, never>, Record<never, never>>,
    '/lcAdjustment': RouteRecordInfo<'/lcAdjustment', '/lcAdjustment', Record<never, never>, Record<never, never>>,
    '/lcApp': RouteRecordInfo<'/lcApp', '/lcApp', Record<never, never>, Record<never, never>>,
    '/loanTermModification': RouteRecordInfo<'/loanTermModification', '/loanTermModification', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/managerBeneficiary': RouteRecordInfo<'/managerBeneficiary', '/managerBeneficiary', Record<never, never>, Record<never, never>>,
    '/managerBranch': RouteRecordInfo<'/managerBranch', '/managerBranch', Record<never, never>, Record<never, never>>,
    '/managerMember': RouteRecordInfo<'/managerMember', '/managerMember', Record<never, never>, Record<never, never>>,
    '/managerPersonal': RouteRecordInfo<'/managerPersonal', '/managerPersonal', Record<never, never>, Record<never, never>>,
    '/promptDraft': RouteRecordInfo<'/promptDraft', '/promptDraft', Record<never, never>, Record<never, never>>,
    '/queryAccessLog': RouteRecordInfo<'/queryAccessLog', '/queryAccessLog', Record<never, never>, Record<never, never>>,
    '/queryAccount': RouteRecordInfo<'/queryAccount', '/queryAccount', Record<never, never>, Record<never, never>>,
    '/queryAmendApp': RouteRecordInfo<'/queryAmendApp', '/queryAmendApp', Record<never, never>, Record<never, never>>,
    '/queryAmendNotice': RouteRecordInfo<'/queryAmendNotice', '/queryAmendNotice', Record<never, never>, Record<never, never>>,
    '/queryBeneficiaryBlcAmount': RouteRecordInfo<'/queryBeneficiaryBlcAmount', '/queryBeneficiaryBlcAmount', Record<never, never>, Record<never, never>>,
    '/queryBlcAmount': RouteRecordInfo<'/queryBlcAmount', '/queryBlcAmount', Record<never, never>, Record<never, never>>,
    '/queryCancelApp': RouteRecordInfo<'/queryCancelApp', '/queryCancelApp', Record<never, never>, Record<never, never>>,
    '/queryClientConnect': RouteRecordInfo<'/queryClientConnect', '/queryClientConnect', Record<never, never>, Record<never, never>>,
    '/queryCompare': RouteRecordInfo<'/queryCompare', '/queryCompare', Record<never, never>, Record<never, never>>,
    '/queryDomesticLcFee': RouteRecordInfo<'/queryDomesticLcFee', '/queryDomesticLcFee', Record<never, never>, Record<never, never>>,
    '/queryDraft': RouteRecordInfo<'/queryDraft', '/queryDraft', Record<never, never>, Record<never, never>>,
    '/queryFpcCtsv': RouteRecordInfo<'/queryFpcCtsv', '/queryFpcCtsv', Record<never, never>, Record<never, never>>,
    '/queryFpcLcRpt': RouteRecordInfo<'/queryFpcLcRpt', '/queryFpcLcRpt', Record<never, never>, Record<never, never>>,
    '/queryInterestRate': RouteRecordInfo<'/queryInterestRate', '/queryInterestRate', Record<never, never>, Record<never, never>>,
    '/queryLc': RouteRecordInfo<'/queryLc', '/queryLc', Record<never, never>, Record<never, never>>,
    '/queryLcApp': RouteRecordInfo<'/queryLcApp', '/queryLcApp', Record<never, never>, Record<never, never>>,
    '/queryLcFeeDetail': RouteRecordInfo<'/queryLcFeeDetail', '/queryLcFeeDetail', Record<never, never>, Record<never, never>>,
    '/queryMarDraft': RouteRecordInfo<'/queryMarDraft', '/queryMarDraft', Record<never, never>, Record<never, never>>,
    '/queryMarLc': RouteRecordInfo<'/queryMarLc', '/queryMarLc', Record<never, never>, Record<never, never>>,
    '/queryNegotiationFee': RouteRecordInfo<'/queryNegotiationFee', '/queryNegotiationFee', Record<never, never>, Record<never, never>>,
    '/queryOutstandLc': RouteRecordInfo<'/queryOutstandLc', '/queryOutstandLc', Record<never, never>, Record<never, never>>,
    '/queryPrint': RouteRecordInfo<'/queryPrint', '/queryPrint', Record<never, never>, Record<never, never>>,
    '/querySar': RouteRecordInfo<'/querySar', '/querySar', Record<never, never>, Record<never, never>>,
    '/rePromptDraft': RouteRecordInfo<'/rePromptDraft', '/rePromptDraft', Record<never, never>, Record<never, never>>,
    '/reviewAmendApp': RouteRecordInfo<'/reviewAmendApp', '/reviewAmendApp', Record<never, never>, Record<never, never>>,
    '/reviewCancelApp': RouteRecordInfo<'/reviewCancelApp', '/reviewCancelApp', Record<never, never>, Record<never, never>>,
    '/reviewDraftApp': RouteRecordInfo<'/reviewDraftApp', '/reviewDraftApp', Record<never, never>, Record<never, never>>,
    '/reviewInterestRate': RouteRecordInfo<'/reviewInterestRate', '/reviewInterestRate', Record<never, never>, Record<never, never>>,
    '/reviewLcApp': RouteRecordInfo<'/reviewLcApp', '/reviewLcApp', Record<never, never>, Record<never, never>>,
    '/sentTrfStatus': RouteRecordInfo<'/sentTrfStatus', '/sentTrfStatus', Record<never, never>, Record<never, never>>,
    '/setBeneficiary': RouteRecordInfo<'/setBeneficiary', '/setBeneficiary', Record<never, never>, Record<never, never>>,
    '/setCustomer': RouteRecordInfo<'/setCustomer', '/setCustomer', Record<never, never>, Record<never, never>>,
    '/setCustomerBranch': RouteRecordInfo<'/setCustomerBranch', '/setCustomerBranch', Record<never, never>, Record<never, never>>,
    '/setGroup': RouteRecordInfo<'/setGroup', '/setGroup', Record<never, never>, Record<never, never>>,
    '/settingSi': RouteRecordInfo<'/settingSi', '/settingSi', Record<never, never>, Record<never, never>>,
    '/webPromptDraft': RouteRecordInfo<'/webPromptDraft', '/webPromptDraft', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/amendAccept.vue': {
      routes: '/amendAccept'
      views: never
    }
    'src/pages/amendAdjustment.vue': {
      routes: '/amendAdjustment'
      views: never
    }
    'src/pages/amendApp.vue': {
      routes: '/amendApp'
      views: never
    }
    'src/pages/amendLcApp.vue': {
      routes: '/amendLcApp'
      views: never
    }
    'src/pages/cancelAdjustment.vue': {
      routes: '/cancelAdjustment'
      views: never
    }
    'src/pages/cancelApp.vue': {
      routes: '/cancelApp'
      views: never
    }
    'src/pages/chargeAmendLc.vue': {
      routes: '/chargeAmendLc'
      views: never
    }
    'src/pages/chargeLc.vue': {
      routes: '/chargeLc'
      views: never
    }
    'src/pages/currentAmendApp.vue': {
      routes: '/currentAmendApp'
      views: never
    }
    'src/pages/currentAmendDraftApp.vue': {
      routes: '/currentAmendDraftApp'
      views: never
    }
    'src/pages/currentCancelApp.vue': {
      routes: '/currentCancelApp'
      views: never
    }
    'src/pages/draftAdjustment.vue': {
      routes: '/draftAdjustment'
      views: never
    }
    'src/pages/draftApp.vue': {
      routes: '/draftApp'
      views: never
    }
    'src/pages/draftRejection.vue': {
      routes: '/draftRejection'
      views: never
    }
    'src/pages/expiredLc.vue': {
      routes: '/expiredLc'
      views: never
    }
    'src/pages/fpcBenBuImp.vue': {
      routes: '/fpcBenBuImp'
      views: never
    }
    'src/pages/fpcCadSdi.vue': {
      routes: '/fpcCadSdi'
      views: never
    }
    'src/pages/info.vue': {
      routes: '/info'
      views: never
    }
    'src/pages/lcAdjustment.vue': {
      routes: '/lcAdjustment'
      views: never
    }
    'src/pages/lcApp.vue': {
      routes: '/lcApp'
      views: never
    }
    'src/pages/loanTermModification.vue': {
      routes: '/loanTermModification'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/managerBeneficiary.vue': {
      routes: '/managerBeneficiary'
      views: never
    }
    'src/pages/managerBranch.vue': {
      routes: '/managerBranch'
      views: never
    }
    'src/pages/managerMember.vue': {
      routes: '/managerMember'
      views: never
    }
    'src/pages/managerPersonal.vue': {
      routes: '/managerPersonal'
      views: never
    }
    'src/pages/promptDraft.vue': {
      routes: '/promptDraft'
      views: never
    }
    'src/pages/queryAccessLog.vue': {
      routes: '/queryAccessLog'
      views: never
    }
    'src/pages/queryAccount.vue': {
      routes: '/queryAccount'
      views: never
    }
    'src/pages/queryAmendApp.vue': {
      routes: '/queryAmendApp'
      views: never
    }
    'src/pages/queryAmendNotice.vue': {
      routes: '/queryAmendNotice'
      views: never
    }
    'src/pages/queryBeneficiaryBlcAmount.vue': {
      routes: '/queryBeneficiaryBlcAmount'
      views: never
    }
    'src/pages/queryBlcAmount.vue': {
      routes: '/queryBlcAmount'
      views: never
    }
    'src/pages/queryCancelApp.vue': {
      routes: '/queryCancelApp'
      views: never
    }
    'src/pages/queryClientConnect.vue': {
      routes: '/queryClientConnect'
      views: never
    }
    'src/pages/queryCompare.vue': {
      routes: '/queryCompare'
      views: never
    }
    'src/pages/queryDomesticLcFee.vue': {
      routes: '/queryDomesticLcFee'
      views: never
    }
    'src/pages/queryDraft.vue': {
      routes: '/queryDraft'
      views: never
    }
    'src/pages/queryFpcCtsv.vue': {
      routes: '/queryFpcCtsv'
      views: never
    }
    'src/pages/queryFpcLcRpt.vue': {
      routes: '/queryFpcLcRpt'
      views: never
    }
    'src/pages/queryInterestRate.vue': {
      routes: '/queryInterestRate'
      views: never
    }
    'src/pages/queryLc.vue': {
      routes: '/queryLc'
      views: never
    }
    'src/pages/queryLcApp.vue': {
      routes: '/queryLcApp'
      views: never
    }
    'src/pages/queryLcFeeDetail.vue': {
      routes: '/queryLcFeeDetail'
      views: never
    }
    'src/pages/queryMarDraft.vue': {
      routes: '/queryMarDraft'
      views: never
    }
    'src/pages/queryMarLc.vue': {
      routes: '/queryMarLc'
      views: never
    }
    'src/pages/queryNegotiationFee.vue': {
      routes: '/queryNegotiationFee'
      views: never
    }
    'src/pages/queryOutstandLc.vue': {
      routes: '/queryOutstandLc'
      views: never
    }
    'src/pages/queryPrint.vue': {
      routes: '/queryPrint'
      views: never
    }
    'src/pages/querySar.vue': {
      routes: '/querySar'
      views: never
    }
    'src/pages/rePromptDraft.vue': {
      routes: '/rePromptDraft'
      views: never
    }
    'src/pages/reviewAmendApp.vue': {
      routes: '/reviewAmendApp'
      views: never
    }
    'src/pages/reviewCancelApp.vue': {
      routes: '/reviewCancelApp'
      views: never
    }
    'src/pages/reviewDraftApp.vue': {
      routes: '/reviewDraftApp'
      views: never
    }
    'src/pages/reviewInterestRate.vue': {
      routes: '/reviewInterestRate'
      views: never
    }
    'src/pages/reviewLcApp.vue': {
      routes: '/reviewLcApp'
      views: never
    }
    'src/pages/sentTrfStatus.vue': {
      routes: '/sentTrfStatus'
      views: never
    }
    'src/pages/setBeneficiary.vue': {
      routes: '/setBeneficiary'
      views: never
    }
    'src/pages/setCustomer.vue': {
      routes: '/setCustomer'
      views: never
    }
    'src/pages/setCustomerBranch.vue': {
      routes: '/setCustomerBranch'
      views: never
    }
    'src/pages/setGroup.vue': {
      routes: '/setGroup'
      views: never
    }
    'src/pages/settingSi.vue': {
      routes: '/settingSi'
      views: never
    }
    'src/pages/webPromptDraft.vue': {
      routes: '/webPromptDraft'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
